'use client';
import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import supabase from '@/lib/supabaseClient';
import { LanguageToggle, useLang } from '@/components/LanguageProvider';

export default function ReviewRequestPage(){
  const {token}=useParams(); const router=useRouter(); const {t,lang}=useLang();
  const [session,setSession]=useState(null); const [request,setRequest]=useState(null); const [loading,setLoading]=useState(true); const [msg,setMsg]=useState('');
  const [form,setForm]=useState({reviewer_name:'',reviewer_role:'',reviewer_company:'',relationship:'',rating:5,review_text:'',consent_publication:true});
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session); if(!data.session){setLoading(false); return;} load(data.session);});},[token]);
  async function load(sess){ const {data,error}=await supabase.from('review_requests').select('*').eq('token',token).eq('status','open').maybeSingle(); if(error||!data){setMsg(lang==='en'?'Request not found or closed.':'Richiesta non trovata o chiusa.'); setLoading(false); return;} setRequest(data); setForm(f=>({...f,reviewer_name:data.reviewer_name||'',reviewer_role:data.reviewer_role||'',reviewer_company:data.reviewer_company||''})); setLoading(false); }
  async function submit(e){ e.preventDefault(); setMsg(''); if(!session?.user?.id){ router.push(`/login?next=/reviews/${token}`); return; } if(!form.review_text.trim()){setMsg('Scrivi il testo della recensione.'); return;} const payload={...form,owner_user_id:request.owner_user_id,reviewer_user_id:session.user.id,request_id:request.id,rating:Number(form.rating),status:'pending'}; const {error}=await supabase.from('portfolio_reviews').insert(payload); if(error){setMsg(error.message); return;} await supabase.from('review_requests').update({status:'completed'}).eq('id',request.id); setMsg(lang==='en'?'Review sent. The portfolio owner will approve it before publication.':'Recensione inviata. Il proprietario del portfolio dovrà approvarla prima della pubblicazione.'); }
  if(loading) return <p style={{padding:30}}>{t.loading}</p>;
  if(!session) return <main className="authPage"><div className="authCard"><LanguageToggle/><h1>{t.reviewerMustLogin}</h1><p className="muted">{lang==='en'?'Registration is required to avoid anonymous or fake reviews.':'La registrazione è obbligatoria per evitare recensioni anonime o false.'}</p><Link className="btn primary" href={`/login?next=/reviews/${token}`}>{t.login}</Link></div></main>;
  if(!request) return <p className="error" style={{padding:30}}>{msg}</p>;
  return <main className="authPage"><div className="authCard" style={{maxWidth:680}}><div className="homeActions"><Link href="/">← Home</Link><LanguageToggle/></div><h1>{lang==='en'?'Write a reference':'Scrivi una referenza'}</h1>{request.message&&<p className="hint">{request.message}</p>}<form onSubmit={submit}><label>Nome<input value={form.reviewer_name} onChange={e=>setForm({...form,reviewer_name:e.target.value})} required/></label><label>Ruolo<input value={form.reviewer_role} onChange={e=>setForm({...form,reviewer_role:e.target.value})}/></label><label>Azienda<input value={form.reviewer_company} onChange={e=>setForm({...form,reviewer_company:e.target.value})}/></label><label>Relazione professionale<input value={form.relationship} onChange={e=>setForm({...form,relationship:e.target.value})} placeholder="Es. collega, manager, cliente"/></label><label>Valutazione<select value={form.rating} onChange={e=>setForm({...form,rating:e.target.value})}>{[5,4,3,2,1].map(x=><option value={x} key={x}>{x}/5</option>)}</select></label><label>Recensione<textarea rows={6} value={form.review_text} onChange={e=>setForm({...form,review_text:e.target.value})} required/></label><label className="check compactCheck"><input type="checkbox" checked={form.consent_publication} onChange={e=>setForm({...form,consent_publication:e.target.checked})}/> Autorizzo la pubblicazione nel portfolio</label><button className="btn primary">Invia recensione</button></form>{msg&&<p className={msg.includes('inviata')||msg.includes('sent')?'success':'error'}>{msg}</p>}</div></main>;
}
