'use client';
import { useEffect,useMemo,useState } from 'react';import supabase from '@/lib/supabaseClient';
const LABELS={
  consultation_requests:{title:'Richieste "Migliora il tuo CV"',hint:'Richieste di consulenza CV inviate dagli utenti.',group:'Consulenze'},
  personal_info:{title:'Profili utenti',hint:'Dati anagrafici e profilo pubblico di ogni utente.',group:'Utenti'},
  subscriptions:{title:'Abbonamenti',hint:'Stato trial/Premium di ogni utente.',group:'Licenze'},
  professional_availability:{title:'Disponibilità professionale',hint:'Preferenze di visibilità e contatto degli utenti.',group:'Utenti'},
  review_requests:{title:'Inviti a lasciare una recensione',hint:'Link generati dagli utenti per ricevere referenze.',group:'Recensioni'},
  portfolio_reviews:{title:'Recensioni ricevute',hint:'Recensioni inviate dai referenti, in attesa o pubblicate.',group:'Recensioni'},
  cv_versions:{title:'Versioni CV',hint:'Varianti di CV salvate dagli utenti.',group:'Contenuti'},
  ai_generations:{title:'Analisi Job Match',hint:'Storico delle analisi AI tra CV e annunci di lavoro.',group:'Contenuti'},
  cookie_settings:{title:'Impostazioni cookie banner',hint:'Testi e opzioni mostrate nel banner cookie.',group:'Configurazione'},
  ai_settings:{title:'Motore Job Match (AI)',hint:'Inserisci una chiave API Anthropic e attiva "is_active" per passare da analisi testuale ad AI in tempo reale.',group:'Configurazione'},
  course_sponsors:{title:'Sponsor corsi (Job Match)',hint:'Ogni riga sostituisce il suggerimento generico con un corso sponsorizzato per quella categoria. "priority" più alto vince se ce n\'è più di uno per la stessa categoria.',group:'Monetizzazione'}
};
const FIELD_LABELS={user_id:'ID utente',owner_id:'ID proprietario',reviewer_user_id:'ID chi recensisce',email:'Email',name:'Nome',phone:'Telefono',source:'Origine',status:'Stato',message:'Messaggio',price_eur:'Prezzo (€)',admin_notes:'Note admin',nome:'Nome',cognome:'Cognome',email_cv:'Email CV',job_title:'Ruolo',public_slug:'Slug pubblico',is_public:'Pubblico',plan:'Piano',trial_ends_at:'Fine trial',current_period_end:'Fine periodo corrente',stripe_customer_id:'ID cliente Stripe',stripe_subscription_id:'ID abbonamento Stripe',open_to_work:'Aperto a opportunità',consulting:'Consulenze',freelance:'Freelance',networking:'Networking',teaching:'Docenze',collaborations:'Collaborazioni',show_in_directory:'Visibile in elenco',contact_message:'Messaggio di contatto',reviewer_email:'Email di chi recensisce',reviewer_name:'Nome di chi recensisce',reviewer_role:'Ruolo di chi recensisce',reviewer_company:'Azienda di chi recensisce',relationship:'Relazione professionale',rating:'Voto (1-5)',review_text:'Testo recensione',consent_publication:'Consenso pubblicazione',title:'Titolo',slug:'Slug',lang:'Lingua',is_premium:'Premium',enabled_sections:'Sezioni abilitate',job_text:'Testo annuncio',match_score:'Punteggio match',matched_keywords:'Keyword trovate',missing_keywords:'Keyword mancanti',banner_title:'Titolo banner',banner_text:'Testo banner',analytics_enabled:'Analytics abilitati',marketing_enabled:'Marketing abilitato',qr_tracking_enabled:'Tracking QR abilitato',is_active:'Attivo',provider:'Provider',api_key:'Chiave API',model:'Modello',category:'Categoria',provider_name:'Nome sponsor',url:'Link corso',logo_url:'URL logo',priority:'Priorità',impressions:'Visualizzazioni',clicks:'Click'};
function fieldLabel(f){return FIELD_LABELS[f]||f}
const READONLY_FIELDS=new Set(['user_id','owner_id','reviewer_user_id','impressions','clicks']);
const STATUS_COLORS={pending:'statusPending',approved:'statusApproved',rejected:'statusRejected',open:'statusOpen',requested:'statusPending',completed:'statusApproved',cancelled:'statusRejected',trialing:'statusPending',active:'statusApproved'};
const CONFIG={consultation_requests:['user_id','email','name','phone','source','status','message','price_eur','admin_notes'],personal_info:['user_id','nome','cognome','email_cv','job_title','public_slug','is_public'],subscriptions:['user_id','plan','status','trial_ends_at','current_period_end','stripe_customer_id','stripe_subscription_id'],professional_availability:['user_id','open_to_work','consulting','freelance','networking','teaching','collaborations','show_in_directory','contact_message'],review_requests:['owner_user_id','reviewer_email','reviewer_name','reviewer_role','reviewer_company','message','status'],portfolio_reviews:['owner_user_id','reviewer_user_id','reviewer_name','reviewer_role','reviewer_company','relationship','rating','review_text','consent_publication','status'],cv_versions:['user_id','title','slug','lang','is_premium','is_public','enabled_sections'],ai_generations:['user_id','job_text','match_score','matched_keywords','missing_keywords'],cookie_settings:['banner_title','banner_text','analytics_enabled','marketing_enabled','qr_tracking_enabled','is_active'],ai_settings:['provider','api_key','model','is_active'],course_sponsors:['category','title','provider_name','url','logo_url','priority','is_active','impressions','clicks']};
const BOOLS=new Set(['open_to_work','consulting','freelance','networking','teaching','collaborations','show_in_directory','consent_publication','is_premium','is_public','analytics_enabled','marketing_enabled','qr_tracking_enabled','is_active']);const NUMS=new Set(['rating','match_score','price_eur']);const JSONS=new Set(['enabled_sections']);const ARRAYS=new Set(['matched_keywords','missing_keywords']);function empty(table){const x={};CONFIG[table].forEach(f=>x[f]=BOOLS.has(f)?false:NUMS.has(f)?(f==='price_eur'?25:0):JSONS.has(f)?'{}':'');return x}function show(v){if(v==null)return'';if(typeof v==='object')return JSON.stringify(v);return String(v)}function clean(form,table){const p={};CONFIG[table].forEach(f=>{let v=form[f];if(BOOLS.has(f))v=!!v;else if(NUMS.has(f))v=Number(v||0);else if(JSONS.has(f)){try{v=JSON.parse(v||'{}')}catch{v={}}}else if(ARRAYS.has(f))v=String(v||'').split(',').map(x=>x.trim()).filter(Boolean);else if(String(v).trim()==='')v=null;p[f]=v});return p}
export default function AdminTableManager(){const tables=Object.keys(CONFIG);const[table,setTable]=useState('consultation_requests');const[rows,setRows]=useState([]);const[form,setForm]=useState(empty('consultation_requests'));const[editId,setEditId]=useState(null);const[msg,setMsg]=useState('');const[q,setQ]=useState('');useEffect(()=>{setForm(empty(table));setEditId(null);load()},[table]);async function load(){setMsg('');const{data,error}=await supabase.from(table).select('*').order('created_at',{ascending:false}).limit(300);if(error)setMsg(error.message);setRows(data||[])}function edit(r){const n=empty(table);CONFIG[table].forEach(f=>{const v=r[f];n[f]=JSONS.has(f)?JSON.stringify(v||{},null,2):ARRAYS.has(f)?(v||[]).join(', '):v??(BOOLS.has(f)?false:'')});setForm(n);setEditId(r.id);window.scrollTo({top:0,behavior:'smooth'})}async function save(e){e.preventDefault();const payload=clean(form,table);const res=editId?await supabase.from(table).update(payload).eq('id',editId):await supabase.from(table).insert(payload);if(res.error)setMsg(res.error.message);else{setMsg(editId?'Riga aggiornata':'Riga creata');setEditId(null);setForm(empty(table));load()}}async function del(r){if(!confirm('Eliminare questa riga?'))return;const{error}=await supabase.from(table).delete().eq('id',r.id);if(error)setMsg(error.message);else{setMsg('Riga eliminata');load()}}const filtered=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())),[rows,q]);
  const groups=useMemo(()=>{
    const g={};
    tables.forEach(tab=>{
      const meta=LABELS[tab]||{title:tab,group:'Altro'};
      g[meta.group]=g[meta.group]||[];
      g[meta.group].push(tab);
    });
    return g;
  },[tables]);
  const currentMeta=LABELS[table]||{title:table,hint:''};
  return <section className="adminPanelCard"><div className="adminTabGroups">{Object.entries(groups).map(([groupName,tabs])=><div className="adminTabGroup" key={groupName}><span className="adminTabGroupLabel">{groupName}</span><div className="adminTabs">{tabs.map(tb=><button key={tb} className={tb===table?'active':''} onClick={()=>setTable(tb)}>{(LABELS[tb]||{}).title||tb}</button>)}</div></div>)}</div><h3>{currentMeta.title}</h3><p className="muted">{currentMeta.hint} <span className="adminTechName">({table})</span></p><form className="quickForm" onSubmit={save}><div className="quickFormGrid">{CONFIG[table].map(f=><label key={f} className={BOOLS.has(f)?'check':''}>{BOOLS.has(f)?<><input type="checkbox" checked={!!form[f]} onChange={e=>setForm({...form,[f]:e.target.checked})}/> {fieldLabel(f)}</>:<>{fieldLabel(f)}{READONLY_FIELDS.has(f)?<input value={form[f]??''} disabled placeholder="generato automaticamente" onChange={e=>setForm({...form,[f]:e.target.value})}/>:['message','review_text','contact_message','job_text','enabled_sections','admin_notes','banner_text'].includes(f)?<textarea rows={3} value={form[f]||''} onChange={e=>setForm({...form,[f]:e.target.value})}/>:<input value={form[f]??''} onChange={e=>setForm({...form,[f]:e.target.value})}/>}</>}</label>)}</div><div className="quickFormActions splitActions"><button type="button" className="btn" onClick={()=>load()}>Aggiorna elenco</button><div><button type="button" className="btn" onClick={()=>{setEditId(null);setForm(empty(table))}}>Nuova riga</button> <button className="btn primary">{editId?'Salva modifiche':'Crea riga'}</button></div></div>{msg&&<p className={msg.includes('error')?'error':'success'}>{msg}</p>}</form><div className="adminSearch"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cerca..."/></div><div className="adminTableWrap"><table className="adminDataTable"><thead><tr><th>Azioni</th>{CONFIG[table].slice(0,8).map(f=><th key={f}>{fieldLabel(f)}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><button onClick={()=>edit(r)}>Modifica</button><button className="danger" onClick={()=>del(r)}>Elimina</button></td>{CONFIG[table].slice(0,8).map(f=><td key={f}>{f==='status'&&r[f]?<span className={`statusBadge ${STATUS_COLORS[r[f]]||'statusOther'}`}>{r[f]}</span>:show(r[f])}</td>)}</tr>)}</tbody></table>{filtered.length===0&&<p className="muted adminEmptyRow">Nessuna riga trovata.</p>}</div></section>}