'use client';
import { fieldVisible, formatDateRange, formatMonthYear, isVisibleInLang, levelLabels } from '@/lib/helpers';
import { useLang } from '@/components/LanguageProvider';
import ImagePreview from '@/components/ImagePreview';
function desc(row,field='description'){ return !row.hide_description && fieldVisible(row,field) && row[field]; }
function sortSkills(skills){ return [...(skills||[])].sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'it',{sensitivity:'base'})); }
export default function CvTemplate({data,qrCode,forcedLang}){ const ctx=useLang(); const lang=forcedLang||ctx.lang; const t=ctx.t; const p=data?.personal_info||{}; const full=[p.nome,p.cognome].filter(Boolean).join(' ') || (lang==='en'?'Your name':'Il tuo nome');
const filter=(arr)=>(arr||[]).filter(x=>!x.is_hidden&&isVisibleInLang(x,lang)); const work=filter(data?.work_experiences); const ed=filter(data?.educations); const langs=filter(data?.languages); const skills=sortSkills(filter(data?.skills)); const awards=filter(data?.awards); const projects=filter(data?.projects); const cases=filter(data?.case_studies);
return <div id="cv-document" className="cv-page">
  <div className="header-flex"><div className="header-main"><h1>{full}</h1>{p.job_title&&<p className="headline">{p.job_title}</p>}<p className="contact-line">{[p.citta_residenza,p.nazione,p.email_cv,p.telefono].filter(Boolean).join(' · ')}</p></div>{p.photo_url&&<div className="avatar-box"><ImagePreview url={p.photo_url} alt={full}/></div>}</div>
  {p.summary&&<section><h2>{lang==='en'?'About me':'Chi sono'}</h2><p>{p.summary}</p></section>}
  {work.length>0&&<section><h2>{lang==='en'?'Experience':'Esperienza'}</h2>{work.map(x=><div className="item" key={x.id}><div className="item-header"><h3>{x.role_title}{fieldVisible(x,'company')&&x.company?` - ${x.company}`:''}</h3>{(fieldVisible(x,'start_date')||fieldVisible(x,'end_date'))&&<span className="item-meta">{formatDateRange(x.start_date,x.end_date,lang)}</span>}</div>{desc(x)&&<p>{x.description}</p>}</div>)}</section>}
  {ed.length>0&&<section><h2>{lang==='en'?'Education':'Formazione'}</h2>{ed.map(x=><div className="item" key={x.id}><div className="item-header"><h3>{x.title}{fieldVisible(x,'institution')&&x.institution?` - ${x.institution}`:''}</h3>{(fieldVisible(x,'start_date')||fieldVisible(x,'end_date'))&&<span className="item-meta">{formatDateRange(x.start_date,x.end_date,lang)}</span>}</div>{<p className="muted-small">{[fieldVisible(x,'field_of_study')?x.field_of_study:'',fieldVisible(x,'location')?x.location:'',fieldVisible(x,'grade')&&x.grade?(lang==='en'?`Grade: ${x.grade}`:`Voto: ${x.grade}`):''].filter(Boolean).join(' · ')}</p>}{desc(x)&&<p>{x.description}</p>}</div>)}</section>}
  {langs.length>0&&<section><h2>{lang==='en'?'Languages':'Lingue'}</h2><div className="lang-list">{langs.map(x=><span className="lang-pill" key={x.id}>{x.lingua}{fieldVisible(x,'livello')?` · ${(levelLabels[x.livello]?.[lang]||x.livello)}`:''}</span>)}</div></section>}
  {skills.length>0&&<section><h2>{lang==='en'?'Skills':'Competenze'}</h2>{skills.map(x=><span className="tag-pill" key={x.id}>{x.name}{!x.hide_score&&fieldVisible(x,'rating')?` · ${x.rating}/5`:''}</span>)}</section>}
  {awards.length>0&&<section><h2>{lang==='en'?'Awards':'Premi e riconoscimenti'}</h2>{awards.map(x=><div className="item" key={x.id}><div className="item-header"><h3>{x.title}{fieldVisible(x,'issuer')&&x.issuer?` - ${x.issuer}`:''}</h3>{fieldVisible(x,'date')&&<span className="item-meta">{formatMonthYear(x.date,lang)}</span>}</div>{desc(x)&&<p>{x.description}</p>}</div>)}</section>}
  {projects.length>0&&<section><h2>{lang==='en'?'Projects':'Progetti'}</h2>{projects.map(x=><div className="item" key={x.id}><div className="item-header"><h3>{x.title}{fieldVisible(x,'role')&&x.role?` - ${x.role}`:''}</h3>{(fieldVisible(x,'start_date')||fieldVisible(x,'end_date'))&&<span className="item-meta">{formatDateRange(x.start_date,x.end_date,lang)}</span>}</div>{desc(x)&&<p>{x.description}</p>}</div>)}</section>}
  {cases.length>0&&<section><h2>Case Study</h2>{cases.map(x=><div className="item" key={x.id}><div className="item-header"><h3>{x.title}</h3>{fieldVisible(x,'date')&&<span className="item-meta">{formatMonthYear(x.date,lang)}</span>}</div>{!x.hide_description&&<>{fieldVisible(x,'context')&&x.context&&<p><b>{lang==='en'?'Context':'Contesto'}:</b> {x.context}</p>}{fieldVisible(x,'solution')&&x.solution&&<p><b>{lang==='en'?'Solution':'Soluzione'}:</b> {x.solution}</p>}{fieldVisible(x,'impact')&&x.impact&&<p><b>{lang==='en'?'Impact':'Impatto'}:</b> {x.impact}</p>}</>}</div>)}</section>}
  {qrCode&&<div className="qr-portfolio-block"><img src={qrCode} alt="QR portfolio"/><p className="qr-small-text"><b>{t.portfolioPhrase1}</b><br/>{t.portfolioPhrase2}</p></div>}
</div> }
