'use client';
import { useMemo, useState } from 'react';
import supabase from '@/lib/supabaseClient';
import { useLang } from '@/components/LanguageProvider';
function emptyFromFields(fields){ const obj={content_lang:'all',cv_visibility:{}}; fields.forEach(f=>{ obj[f.name]=f.type==='checkbox'?false:(f.default??''); if(f.cvField) obj.cv_visibility[f.name]=true; }); return obj; }
function cleanPayload(payload, fields, userId){ const next={...payload,user_id:userId,cv_visibility:{...(payload.cv_visibility||{})}}; fields.forEach(f=>{ if(f.type==='date'&&next[f.name]==='') next[f.name]=null; if(f.type==='number') next[f.name]=Math.max(Number(f.min??0),Math.min(Number(f.max??999),Number(next[f.name]||f.default||0))); if(typeof next[f.name]==='string') next[f.name]=next[f.name].trim(); }); return next; }
function mainLabel(row){ return row.role_title||row.title||row.name||row.lingua||'Elemento senza titolo'; }
function secondLabel(row){ return row.company||row.institution||row.issuer||row.role||row.category||row.livello||row.description||row.impact||'Elemento salvato'; }
export default function SectionManager({title,description,table,fields,rows,userId,onChange,globalSkills=[]}){ const {t}=useLang(); const initial=useMemo(()=>emptyFromFields(fields),[fields]); const [form,setForm]=useState(initial); const [editingId,setEditingId]=useState(null); const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const requiredField=fields.find(f=>f.required)?.name||fields.find(f=>!['date','textarea','checkbox','select','number'].includes(f.type||'text'))?.name; const isSkills=table==='skills'; const skillExists=isSkills&&form.name&&globalSkills.map(s=>s.toLowerCase()).includes(String(form.name).toLowerCase()); const showNewSkillNotice=isSkills&&form.name&&!skillExists;
function startNew(){ setForm(emptyFromFields(fields)); setEditingId(null); setOpen(true); setError(''); setSuccess(''); }
function editRow(row){ const next=emptyFromFields(fields); fields.forEach(f=>{ next[f.name]=row[f.name]??(f.type==='checkbox'?false:''); }); next.content_lang=row.content_lang||'all'; next.cv_visibility={...(next.cv_visibility||{}),...(row.cv_visibility||{})}; setForm(next); setEditingId(row.id); setOpen(true); setError(''); setSuccess(''); }
function closeForm(){ setForm(emptyFromFields(fields)); setEditingId(null); setOpen(false); setError(''); }
function setField(name,value){ setForm(prev=>({...prev,[name]:value})); }
function setVisibility(name,value){ setForm(prev=>({...prev,cv_visibility:{...(prev.cv_visibility||{}),[name]:value}})); }
async function saveItem(keepOpen=false){ try{ setBusy(true); setError(''); setSuccess(''); const payload=cleanPayload(form,fields,userId); if(requiredField&&!payload[requiredField]){ setError('Compila almeno il campo principale prima di salvare.'); return; } const q=editingId?supabase.from(table).update(payload).eq('id',editingId).eq('user_id',userId).select().single():supabase.from(table).insert(payload).select().single(); const result=await q; if(result.error){ setError(result.error.message); return; } await onChange?.(); if(keepOpen&&!editingId){ setForm(emptyFromFields(fields)); setSuccess('Elemento salvato. Puoi inserirne subito un altro.'); return; } setForm(emptyFromFields(fields)); setEditingId(null); setOpen(false); setSuccess(editingId?'Elemento aggiornato.':'Elemento salvato.'); setTimeout(()=>setSuccess(''),2500); }catch(e){ setError(e?.message||'Errore di rete durante il salvataggio. Riprova tra qualche secondo.'); }finally{ setBusy(false); } }
async function remove(id){ if(!confirm(t.confirmDelete)) return; try{ const {error}=await supabase.from(table).delete().eq('id',id).eq('user_id',userId); if(error){ setError(error.message); return; } await onChange?.(); }catch(e){ setError(e?.message||'Errore di rete durante eliminazione.'); } }
return <section className="smartSection wideSection"><div className="smartSectionHeader"><div><h2>{title}</h2><p>{description}</p><span className="sectionCount">{rows.length} elementi salvati</span></div><button className="btn primary" type="button" onClick={open?closeForm:startNew}>{open?t.close:`${t.add} ${title}`}</button></div>
{open&&<form className="quickForm" onSubmit={e=>{e.preventDefault();saveItem(false);}}><h3>{editingId?`${t.edit} ${title}`:`${t.add} ${title}`}</h3>{isSkills&&<p className="hint">{t.catalogHint}</p>}<div className="quickFormGrid"><label>{t.contentLang}<select value={form.content_lang||'all'} onChange={e=>setField('content_lang',e.target.value)}><option value="all">{t.both}</option><option value="it">{t.italian}</option><option value="en">{t.english}</option></select></label>{fields.map(f=><div key={f.name} className={f.type==='textarea'?'wide fieldWithVisibility':'fieldWithVisibility'}><label className={f.type==='checkbox'?'check compactCheck':''}><span>{f.label}</span>{f.type==='textarea'?<textarea value={form[f.name]||''} onChange={e=>setField(f.name,e.target.value)} rows={3}/>:f.type==='select'?<select value={form[f.name]??''} onChange={e=>setField(f.name,e.target.value)}>{(f.options||[]).map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='checkbox'?<input type="checkbox" checked={Boolean(form[f.name])} onChange={e=>setField(f.name,e.target.checked)}/>:<input type={f.type||'text'} min={f.min} max={f.max} list={f.listId} value={form[f.name]??''} onChange={e=>setField(f.name,e.target.value)}/>}</label>{f.cvField&&<label className="check miniCheck"><input type="checkbox" checked={form.cv_visibility?.[f.name]!==false} onChange={e=>setVisibility(f.name,e.target.checked)}/> {t.showField}</label>}</div>)}</div>{showNewSkillNotice&&<p className="warning">{t.newSkillNotice}</p>}<div className="quickFormActions splitActions"><button className="btn" type="button" onClick={closeForm}>{t.cancel}</button><div>{!editingId&&<button className="btn" type="button" disabled={busy} onClick={()=>saveItem(true)}>{busy?t.saving:t.saveAddAnother}</button>} <button className="btn primary" type="submit" disabled={busy}>{busy?t.saving:(editingId?t.update:t.saveClose)}</button></div></div>{error&&<p className="error">{error}</p>}{success&&<p className="success">{success}</p>}</form>}
<div className="simpleRows">{rows.length===0?<p className="muted">{t.noItems}</p>:rows.map(row=><div className="simpleRow" key={row.id}><div className="simpleRowMain"><strong>{mainLabel(row)}</strong><span>{secondLabel(row)}{row.rating?` · ${row.rating}/5`:''}</span></div><div className="simpleRowActions">{row.content_lang&&row.content_lang!=='all'&&<span className="hiddenPill lightPill">{row.content_lang.toUpperCase()}</span>}{row.is_hidden&&<span className="hiddenPill">{t.hidden}</span>}<button type="button" onClick={()=>editRow(row)}>{t.edit}</button><button type="button" className="danger" onClick={()=>remove(row.id)}>{t.delete}</button></div></div>)}</div></section> }
