'use client';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import supabase from '@/lib/supabaseClient';
import { LanguageToggle, useLang } from '@/components/LanguageProvider';

function dayKey(d){
  const date=new Date(d);
  return Number.isNaN(date.getTime())?'':date.toISOString().slice(0,10);
}
function isPremiumSubscription(sub){
  if(!sub) return false;
  if(sub.status==='trialing'||sub.status==='active'||sub.plan==='premium'||sub.plan==='pro') return true;
  return Boolean(sub.trial_ends_at && new Date(sub.trial_ends_at)>new Date());
}

export default function AnalyticsPage(){
  const router=useRouter();
  const {t,lang}=useLang();
  const [session,setSession]=useState(null);
  const [loading,setLoading]=useState(true);
  const [events,setEvents]=useState([]);
  const [subscription,setSubscription]=useState(null);
  const [warning,setWarning]=useState('');
  const [error,setError]=useState('');

  useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(!data.session){router.push('/login');return;} setSession(data.session);});},[router]);
  useEffect(()=>{if(session?.user?.id) load();},[session?.user?.id]);

  async function load(){
    try{
      setLoading(true); setError(''); setWarning('');
      const userId=session.user.id;

      try{
        let {data:sub,error:subError}=await supabase.from('subscriptions').select('*').eq('user_id',userId).maybeSingle();
        if(subError) throw subError;
        if(!sub){
          const res=await supabase.from('subscriptions').insert({user_id:userId}).select('*').single();
          if(res.error) throw res.error;
          sub=res.data;
        }
        setSubscription(sub);
      }catch(e){
        setSubscription({plan:'free',status:'active'});
        setWarning(lang==='en'
          ? 'Subscription table not ready: basic analytics are still visible. Run supabase/migration_v10_monetization.sql to enable premium logic.'
          : 'Tabella abbonamenti non pronta: le statistiche base restano visibili. Esegui supabase/migration_v10_monetization.sql per abilitare la logica Premium.');
      }

      const since=new Date(Date.now()-30*24*60*60*1000).toISOString();
      const {data,error}=await supabase
        .from('analytics_events')
        .select('*')
        .eq('profile_user_id',userId)
        .gte('created_at',since)
        .order('created_at',{ascending:false});
      if(error) throw error;
      setEvents(data||[]);
    }catch(e){
      setError(`${e.message}. Esegui supabase/migration_v8_incrementale.sql se manca la tabella analytics_events o qualche colonna.`);
    }finally{ setLoading(false); }
  }

  const hasPremium=isPremiumSubscription(subscription);
  const stats=useMemo(()=>{
    const views=events.filter(e=>e.event_type==='profile_view');
    const scans=events.filter(e=>e.event_type==='qr_scan');
    const byDay={};
    events.forEach(e=>{
      const k=dayKey(e.created_at); if(!k) return;
      byDay[k]=byDay[k]||{profile_view:0,qr_scan:0};
      if(e.event_type==='profile_view'||e.event_type==='qr_scan') byDay[k][e.event_type]+=1;
    });
    return {views:views.length,scans:scans.length,total:events.length,byDay:Object.entries(byDay).sort(([a],[b])=>a.localeCompare(b))};
  },[events]);

  if(loading) return <p style={{padding:30}}>{t.loading}</p>;
  return <>
    <header className="topbar"><strong>QR Curriculum</strong><nav><LanguageToggle/><Link href="/dashboard">{t.dashboard}</Link><Link href="/radar-skill">{t.radarSkill}</Link></nav></header>
    <section className="heroPanel"><div className="cleanHero"><p className="eyebrow">Analytics</p><h1>{lang==='en'?'Profile statistics':'Statistiche profilo'}</h1><p>{lang==='en'?'Profile views and QR scans recorded from the public CV.':'Visualizzazioni profilo e scansioni QR registrate dal CV pubblico.'}</p></div></section>
    {warning&&<p className="bigError warning">{warning}</p>}
    {error&&<p className="bigError error">{error}</p>}
    <section className="analyticsGrid">
      <div className="metricCard"><span>{t.views}</span><strong>{stats.views}</strong></div>
      <div className="metricCard"><span>{t.scans}</span><strong>{stats.scans}</strong></div>
      <div className="metricCard"><span>{t.totalEvents}</span><strong>{stats.total}</strong></div>
    </section>
    <section className="smartSection wideSection analyticsInfoBox">
      <h2>{lang==='en'?'How statistics are counted':'Come vengono conteggiate le statistiche'}</h2>
      <p className="muted">{lang==='en'
        ? 'A profile view is recorded when someone opens /qrcv/username. A QR scan is recorded when the same public profile is opened with the qr=1 parameter generated by the QR code.'
        : 'Una visualizzazione viene registrata quando qualcuno apre /qrcv/nomeutente. Una scansione QR viene registrata quando lo stesso profilo pubblico viene aperto con il parametro qr=1 generato dal QR code.'}</p>
      <button className="btn" type="button" onClick={load}>{lang==='en'?'Refresh statistics':'Aggiorna statistiche'}</button>
    </section>
    {!hasPremium&&<section className="smartSection wideSection analyticsInfoBox"><div className="paywallBox"><h2>{t.basicAnalytics}</h2><p>{lang==='en'?'Basic totals are always visible. Daily trend and latest events are Premium features after the trial.':'I totali base restano sempre visibili. Andamento giornaliero e ultimi eventi sono funzioni Premium dopo il periodo di prova.'}</p><button className="btn primary">{t.upgrade}</button></div></section>}
    {hasPremium&&<section className="smartSection wideSection analyticsInfoBox"><h2>{t.dailyTrend}</h2><div className="barList">{stats.byDay.length===0?<p className="muted">{t.noEvents}</p>:stats.byDay.map(([day,v])=><div className="barRow" key={day}><span>{day}</span><div><i style={{width:`${Math.min(100,Math.max(3,v.profile_view*10))}%`}}/><b>{v.profile_view} visite</b></div><div><i className="qrBar" style={{width:`${Math.min(100,Math.max(3,v.qr_scan*10))}%`}}/><b>{v.qr_scan} scan</b></div></div>)}</div></section>}
    {hasPremium&&<section className="smartSection wideSection analyticsInfoBox"><h2>{t.lastEvents}</h2>{events.length===0?<p className="muted">{t.noEvents}</p>:events.slice(0,30).map(e=><p key={e.id}><b>{e.event_type}</b> · {new Date(e.created_at).toLocaleString(lang==='en'?'en-US':'it-IT')} · {e.referrer||'nessun referrer'}</p>)}</section>}
  </>;
}
