'use client';
import { formatMonthYear, levelLabels } from '@/lib/helpers';
export default function CvTemplate({ data, qrCode }){
  const p=data.personal_info||{}; const fullName=[p.nome,p.cognome].filter(Boolean).join(' ')||'Il tuo nome';
  const work=data.work_experiences||[], educations=data.educations||[], languages=data.languages||[], skills=data.skills||[], awards=data.awards||[], projects=data.projects||[], caseStudies=data.case_studies||[];
  return <div className="cv-page" id="cv-document"><div className="header-flex"><div className="header-main"><h1>{fullName}</h1>{p.job_title?<p className="headline">{p.job_title}</p>:null}<p className="contact-line">{[p.citta_residenza,p.nazione,p.email_cv,p.telefono].filter(Boolean).join(' · ')}</p></div>{p.photo_url?<div className="avatar-box"><img src={p.photo_url} alt="Foto profilo"/></div>:null}</div>
  {p.summary?<section className="section"><h2>Chi sono</h2><p>{p.summary}</p></section>:null}
  {work.length>0?<section className="section"><h2>Esperienza</h2>{work.map(we=><div className="item" key={we.id}><div className="item-header"><h3>{we.role_title}{we.company?` — ${we.company}`:''}</h3><div className="item-meta">{formatMonthYear(we.start_date)} → {we.end_date?formatMonthYear(we.end_date):'Presente'}</div></div>{we.description?<p>{we.description}</p>:null}</div>)}</section>:null}
  {educations.length>0?<section className="section"><h2>Formazione</h2>{educations.map(ed=><div className="item" key={ed.id}><div className="item-header"><div><h3>{ed.title}{ed.institution?` — ${ed.institution}`:''}</h3><div className="item-meta">{[ed.field_of_study,ed.location].filter(Boolean).join(' — ')}</div>{ed.grade?<div className="item-meta">Voto: {ed.grade}</div>:null}</div><div className="item-meta">{formatMonthYear(ed.start_date)} → {formatMonthYear(ed.end_date)}</div></div></div>)}</section>:null}
  {languages.length>0?<section className="section"><h2>Lingue</h2><div className="lang-list">{languages.map(l=><span className="lang-pill" key={l.id}>{l.lingua} — {levelLabels[l.livello]||l.livello}</span>)}</div></section>:null}
  {skills.length>0?<section className="section"><h2>Competenze</h2>{skills.map(sk=><span className="tag-pill" key={sk.id}>{sk.name}</span>)}</section>:null}
  {awards.length>0?<section className="section"><h2>Premi &amp; Riconoscimenti</h2>{awards.map(aw=><div className="item" key={aw.id}><div className="item-header"><h3>{aw.title}</h3><div className="item-meta">{[formatMonthYear(aw.date),aw.issuer].filter(Boolean).join(' — ')}</div></div></div>)}</section>:null}
  {projects.length>0?<section className="section"><h2>Progetti</h2>{projects.map(pr=><div className="item" key={pr.id}><div className="item-header"><h3>{pr.title}</h3><div className="item-meta">{formatMonthYear(pr.start_date)}{pr.end_date?` → ${formatMonthYear(pr.end_date)}`:''}</div></div>{pr.description?<p>{pr.description}</p>:null}</div>)}</section>:null}
  {caseStudies.length>0?<section className="section"><h2>Case Study</h2>{caseStudies.map(cs=><div className="item" key={cs.id}><div className="item-header"><h3>{cs.title}</h3><div className="item-meta">{formatMonthYear(cs.date)}</div></div>{cs.impact?<p>{cs.impact}</p>:null}</div>)}</section>:null}
  {qrCode?<div className="qr-portfolio-block"><img src={qrCode} alt="QR code CV"/><div className="qr-small-text">Ho reso il mio CV interattivo.<br/>Scansiona per vedere il mio portfolio completo.</div></div>:null}</div>;
}
