'use client';
import { useState } from 'react';
import { supabase } from '@/lib/supabaseClient';
function emptyFromFields(fields){return fields.reduce((acc,field)=>{acc[field.name]=field.type==='checkbox'?false:'';return acc;},{});} function cleanPayload(payload,fields){const next={...payload}; fields.forEach(field=>{if(field.type==='date'&&next[field.name]==='') next[field.name]=null;}); return next;}
export default function SectionManager({title,description,table,fields,rows,userId,onChange}){
 const [form,setForm]=useState(emptyFromFields(fields)); const [editingId,setEditingId]=useState(null); const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 function editRow(row){const next=emptyFromFields(fields); fields.forEach(field=>{next[field.name]=row[field.name]??(field.type==='checkbox'?false:'');}); setForm(next); setEditingId(row.id); setOpen(true); setError('');}
 function reset(){setForm(emptyFromFields(fields)); setEditingId(null); setOpen(false); setError('');}
 async function save(e){e.preventDefault(); setBusy(true); setError(''); const payload=cleanPayload({...form,user_id:userId},fields); const query=editingId?supabase.from(table).update(payload).eq('id',editingId).eq('user_id',userId):supabase.from(table).insert(payload); const {error:saveError}=await query; setBusy(false); if(saveError){setError(saveError.message);return;} reset(); onChange();}
 async function remove(id){if(!window.confirm('Vuoi eliminare questo elemento?')) return; const {error:deleteError}=await supabase.from(table).delete().eq('id',id).eq('user_id',userId); if(deleteError){setError(deleteError.message);return;} onChange();}
 return <section className="smartSection"><div className="smartSectionHeader"><div><h2>{title}</h2><p>{description||'Aggiungi, modifica o nascondi gli elementi di questa sezione.'}</p></div><button className="btn primary" type="button" onClick={()=>setOpen(!open)}>{open?'Chiudi':`Aggiungi ${title}`}</button></div>
 {open?<form className="quickForm" onSubmit={save}><div className="quickFormHead"><strong>{editingId?`Modifica ${title}`:`Nuovo elemento: ${title}`}</strong><button className="linkButton noMargin" type="button" onClick={reset}>Annulla</button></div><div className="quickFormGrid">{fields.map(field=><label key={field.name} className={field.type==='textarea'?'wide':field.type==='checkbox'?'check compactCheck':''}><span>{field.label}</span>{field.type==='textarea'?<textarea value={form[field.name]||''} onChange={e=>setForm({...form,[field.name]:e.target.value})} rows={3}/>:field.type==='select'?<select value={form[field.name]||''} onChange={e=>setForm({...form,[field.name]:e.target.value})}>{(field.options||[]).map(o=><option value={o.value} key={o.value}>{o.label}</option>)}</select>:field.type==='checkbox'?<input type="checkbox" checked={Boolean(form[field.name])} onChange={e=>setForm({...form,[field.name]:e.target.checked})}/>:<input type={field.type||'text'} value={form[field.name]||''} onChange={e=>setForm({...form,[field.name]:e.target.value})}/>}</label>)}</div><div className="quickFormActions"><button className="btn primary" disabled={busy}>{busy?'Salvataggio...':editingId?'Aggiorna elemento':'Salva elemento'}</button></div></form>:null}
 {error?<p className="error">{error}</p>:null}<div className="simpleRows">{rows.length===0?<div className="emptyState">Nessun elemento inserito. Clicca su “Aggiungi” per iniziare.</div>:null}{rows.map(row=><div className="simpleRow" key={row.id}><div className="simpleRowMain"><strong>{row.role_title||row.title||row.name||row.lingua}</strong><span>{row.company||row.institution||row.issuer||row.role||row.livello||row.description||row.impact||'Elemento salvato'}</span></div><div className="simpleRowActions">{row.is_hidden?<span className="hiddenPill">Nascosto</span>:null}<button type="button" onClick={()=>editRow(row)}>Modifica</button><button type="button" className="danger" onClick={()=>remove(row.id)}>Elimina</button></div></div>)}</div></section>;
}
