export const SKILL_CATEGORIES=['Leadership & Management','Operations','Project Management','Data & Analytics','Technology','Engineering','Finance & Business','Sales & Marketing','Communication','Supply Chain','Quality & Improvement','Industry Expertise'];
export const COURSE_LIBRARY={'Leadership & Management':['Leadership fundamentals','People management','Coaching and mentoring'],Operations:['Operations management','Production planning','Process design'],'Project Management':['Project management fundamentals','Agile and Scrum','Risk management'],'Data & Analytics':['Advanced Excel dashboards','Power BI fundamentals','Data analysis and statistics'],Technology:['SQL fundamentals','Python for professionals','ERP and digital tools'],Engineering:['Industrial engineering basics','CAD/CAM fundamentals','Technical problem solving'],'Finance & Business':['Business analysis','Budgeting and controlling','Business model fundamentals'],'Sales & Marketing':['Digital marketing fundamentals','Sales strategy','Personal branding'],Communication:['Public speaking','Professional writing','Stakeholder communication'],'Supply Chain':['Supply chain management','Inventory and MRP','Logistics fundamentals'],'Quality & Improvement':['Lean Six Sigma fundamentals','Root cause analysis','Continuous improvement'],'Industry Expertise':['Sector-specific certification','Portfolio project','Professional specialization']};
export const levelLabels={native:{it:'Madrelingua',en:'Native'},c2:{it:'C2',en:'C2'},c1:{it:'C1',en:'C1'},b2:{it:'B2',en:'B2'},b1:{it:'B1',en:'B1'},a2:{it:'A2',en:'A2'},a1:{it:'A1',en:'A1'},basic:{it:'Base',en:'Basic'}};
export function getSiteUrl(){const env=(process.env.NEXT_PUBLIC_SITE_URL||'').replace(/\/$/,'');if(env&&!env.includes('localhost')&&!env.includes('127.0.0.1'))return env;if(typeof window!=='undefined'&&window.location?.origin)return window.location.origin;return env||'http://localhost:3000'}
export function makePublicUrl(slug,lang){return slug?`${getSiteUrl()}/qrcv/${slug}${lang==='en'?'?lang=en':''}`:''}
export function makeQrUrl(slug){return slug?`${getSiteUrl()}/qrcv/${slug}?qr=1`:''}
export function slugify(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')}
export function makePublicSlug({nome='',cognome='',email=''}={}){const base=slugify([nome,cognome].filter(Boolean).join('-'))||slugify((email||'').split('@')[0])||'profilo';return `${base}-${Math.random().toString(16).slice(2,8)}`}
export function formatMonthYear(date,lang='it'){if(!date)return'';const d=new Date(`${date}T00:00:00`);if(Number.isNaN(d.getTime()))return'';return d.toLocaleDateString(lang==='en'?'en-US':'it-IT',{month:'2-digit',year:'numeric'})}
export function formatDateRange(start,end,lang='it'){const s=formatMonthYear(start,lang);const e=end?formatMonthYear(end,lang):(s?(lang==='en'?'Now':'Adesso'):'');if(s&&e)return `${s} - ${e}`;return s||e||''}
export function cleanDateFields(payload,fields){const next={...payload};fields.forEach(f=>{if(next[f]==='')next[f]=null});return next}
export function restoreScrollAfter(fn){const y=typeof window!=='undefined'?window.scrollY:0;return Promise.resolve(fn()).finally(()=>{if(typeof window!=='undefined')requestAnimationFrame(()=>window.scrollTo({top:y,behavior:'instant'}))})}
export function normalizeCategory(cat){const map={'Digital':'Technology','Digital & Data':'Data & Analytics','Digital, AI & Automazione':'Technology','Data Analysis & Reporting':'Data & Analytics','Gestione Progetti':'Project Management','Project & Process Management':'Project Management','Comunicazione':'Communication','Comunicazione & Public Speaking':'Communication','Communication & Collaboration':'Communication','Leadership':'Leadership & Management','Leadership & People Management':'Leadership & Management','Tecniche di Settore':'Industry Expertise','Fashion, Product & Manufacturing':'Industry Expertise','Finance, Legal & Business':'Finance & Business','Analisi & Problem Solving':'Quality & Improvement','Problem Solving & Continuous Improvement':'Quality & Improvement','Creativita & Design':'Industry Expertise','Creatività & Design':'Industry Expertise','Creatività, Design & UX':'Industry Expertise','Altro':'Industry Expertise','Altro / Settoriale':'Industry Expertise','Operations & Process Improvement':'Operations','Quality Management':'Quality & Improvement','Supply Chain & Logistics':'Supply Chain','Information Technology':'Technology','Engineering & Technical':'Engineering','Sales, Marketing & Personal Branding':'Sales & Marketing','Education & Training':'Leadership & Management','Research & Innovation':'Industry Expertise','Languages':'Communication'};return SKILL_CATEGORIES.includes(cat)?cat:(map[cat]||'Industry Expertise')}
export function skillExperienceYears(acquiredDate){if(!acquiredDate)return null;const start=new Date(`${acquiredDate}T00:00:00`);if(Number.isNaN(start.getTime()))return null;const now=new Date();let years=(now-start)/(365.25*24*60*60*1000);if(years<0)years=0;return Math.round(years*10)/10}
export function skillExperienceLabel(acquiredDate,lang='it'){const y=skillExperienceYears(acquiredDate);if(y===null)return'';if(y<0.1)return lang==='en'?'less than 1 year':'meno di 1 anno';const rounded=Number.isInteger(y)?String(Math.round(y)):String(y).replace('.',',');return lang==='en'?`${String(y).replace(',','.')} yrs`:`${rounded} anni`}
export function isVisibleInLang(row,lang){return !row?.content_lang||row.content_lang==='all'||row.content_lang===lang}
export function fieldVisible(row,field){if(row?.is_hidden)return false;const v=row?.cv_visibility||{};if(Object.prototype.hasOwnProperty.call(v,field))return Boolean(v[field]);return true}
function suggestSkillsForCategory(category){const map={'Leadership & Management':['People management','Team leadership','Coaching'],Operations:['Production planning','Process design','Capacity planning'],'Project Management':['Agile planning','Risk management','Roadmap management'],'Data & Analytics':['Power BI','Advanced Excel','Statistics'],Technology:['SQL','Python','ERP systems'],Engineering:['CAD/CAM','Industrial engineering','Technical problem solving'],'Finance & Business':['Budgeting','Costing','Business analysis'],'Sales & Marketing':['Digital marketing','Sales strategy','Personal branding'],Communication:['Public speaking','Presentation skills','Stakeholder management'],'Supply Chain':['MRP','Inventory management','Logistics'],'Quality & Improvement':['Lean Six Sigma','Kaizen','Root cause analysis'],'Industry Expertise':['Sector specialization','Domain knowledge','Portfolio project']};return map[category]||map['Industry Expertise']}
export function computeSkillInsights(skills){const visible=(skills||[]).filter(s=>!s.is_hidden);const byCat=new Map(SKILL_CATEGORIES.map(c=>[c,[]]));visible.forEach(s=>{const cat=normalizeCategory(s.category);byCat.get(cat).push(Number(s.rating||0))});const radar=SKILL_CATEGORIES.map(category=>{const values=byCat.get(category)||[];const avg=values.length?values.reduce((a,b)=>a+b,0)/values.length:0;return{category,count:values.length,avg:Number(avg.toFixed(2))}});const coverage=radar.filter(r=>r.count>0).length/SKILL_CATEGORIES.length;const avg=visible.length?visible.reduce((a,s)=>a+Number(s.rating||0),0)/visible.length:0;const score=Math.max(0,Math.min(100,Math.round((avg/5)*82+coverage*18)));const weak=radar.filter(r=>r.avg>0&&r.avg<3.5).sort((a,b)=>a.avg-b.avg).slice(0,3);const empty=radar.filter(r=>r.count===0&&r.category!=='Industry Expertise').slice(0,3);const suggestions=[...weak,...empty].slice(0,5).map(r=>({category:r.category,reason:r.count?`Media ${r.avg}/5: area da rafforzare.`:'Categoria non ancora coperta nel profilo.',skills:suggestSkillsForCategory(r.category),courses:COURSE_LIBRARY[r.category]||COURSE_LIBRARY['Industry Expertise']}));return{radar,score,suggestions,avg:Number(avg.toFixed(2)),coverage:Number((coverage*100).toFixed(0))}}
export function computeWorkerScore({personal_info={},skills=[],work_experiences=[],educations=[],projects=[],case_studies=[],languages=[],portfolio_reviews=[]}={}){
  const skill=computeSkillInsights(skills);
  const visibleSkills=(skills||[]).filter(x=>!x.is_hidden);
  const profileFields=['nome','cognome','job_title','summary','email_cv','telefono','citta_residenza','photo_url','public_slug'];
  const completeness=Math.round((profileFields.filter(f=>String(personal_info?.[f]||'').trim()).length/profileFields.length)*100);
  const expCount=(work_experiences||[]).filter(x=>!x.is_hidden).length;
  const eduCount=(educations||[]).filter(x=>!x.is_hidden).length;
  const projectCount=[...(projects||[]),...(case_studies||[])].filter(x=>!x.is_hidden).length;
  const langCount=(languages||[]).filter(x=>!x.is_hidden).length;
  const reviews=(portfolio_reviews||[]).filter(r=>r.status==='approved'||r.consent_publication);
  const avgReview=reviews.length?reviews.reduce((a,r)=>a+Number(r.rating||0),0)/reviews.length:0;
  const skillQuality=visibleSkills.length?Math.round((visibleSkills.slice().sort((a,b)=>Number(b.rating||0)-Number(a.rating||0)).slice(0,20).reduce((a,s)=>a+Number(s.rating||0),0)/Math.min(20,visibleSkills.length))/5*100):0;
  const skillCoverage=Number(skill.coverage||0);
  const experienceEvidence=Math.min(100,Math.round(expCount*15+projectCount*16+eduCount*10+langCount*5));
  const reputation=Math.min(100,Math.round((avgReview/5)*60+Math.min(40,reviews.length*10)));
  const rarityBonus=Math.min(100,Math.round(skill.rarityScore||0));
  const score=Math.max(0,Math.min(100,Math.round(completeness*.15+skillQuality*.30+skillCoverage*.15+experienceEvidence*.20+reputation*.10+rarityBonus*.10)));
  let label='Profilo Iniziale';
  if(score>=90)label='Elite Profile';else if(score>=80)label='Top Performer';else if(score>=65)label='Professionista Avanzato';else if(score>=50)label='Professionista';else if(score>=30)label='Profilo Base';
  return{score,label,details:{profileCompleteness:completeness,skillQuality,skillCoverage,experienceEvidence,reputation,rarityBonus,skillScore:skill.score,coverage:skillCoverage,formula:'15% completezza profilo + 30% qualita skill + 15% copertura categorie + 20% esperienza verificabile + 10% reputazione + 10% rarita skill'}}
}
