export const SKILL_CATEGORIES = ['Digital','Gestione Progetti','Comunicazione','Leadership','Tecniche di Settore','Analisi & Problem Solving','Creatività & Design','Altro'];
export const COURSE_LIBRARY = {
  Digital:['Excel avanzato e dashboard','Power BI per principianti','AI tools per il lavoro quotidiano'],
  'Gestione Progetti':['Project management pratico','Agile planning','Gestione priorità e roadmap'],
  Comunicazione:['Public speaking efficace','Scrittura professionale','Storytelling per presentazioni'],
  Leadership:['Leadership situazionale','Feedback e coaching','Gestione conflitti'],
  'Tecniche di Settore':['Certificazione professionale di settore','Qualità e controllo processo','Supply chain e operations'],
  'Analisi & Problem Solving':['Root cause analysis','Lean Six Sigma base','Problem solving A3'],
  'Creatività & Design':['Design thinking','Figma per prototipi','UX fundamentals'],
  Altro:['Corso verticale di settore','Portfolio project guidato','Certificazione specialistica']
};
export const levelLabels = { native:{it:'Madrelingua',en:'Native'}, c2:{it:'C2',en:'C2'}, c1:{it:'C1',en:'C1'}, b2:{it:'B2',en:'B2'}, b1:{it:'B1',en:'B1'}, a2:{it:'A2',en:'A2'}, a1:{it:'A1',en:'A1'}, basic:{it:'Base',en:'Basic'} };
export function getSiteUrl(){ const env=(process.env.NEXT_PUBLIC_SITE_URL||'').replace(/\/$/,''); if(env && !env.includes('localhost') && !env.includes('127.0.0.1')) return env; if(typeof window!=='undefined' && window.location?.origin) return window.location.origin; return env || 'http://localhost:3000'; }
export function makePublicUrl(slug, lang){ return slug ? `${getSiteUrl()}/qrcv/${slug}${lang==='en'?'?lang=en':''}` : ''; }
export function makeQrUrl(slug){ return slug ? `${getSiteUrl()}/qrcv/${slug}?qr=1` : ''; }
export function slugify(value){ return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,''); }
export function makePublicSlug({nome='',cognome='',email=''}={}){ const base=slugify([nome,cognome].filter(Boolean).join('-')) || slugify((email||'').split('@')[0]) || 'profilo'; return `${base}-${Math.random().toString(16).slice(2,8)}`; }
export function formatMonthYear(date, lang='it'){ if(!date) return ''; const d=new Date(`${date}T00:00:00`); if(Number.isNaN(d.getTime())) return ''; return d.toLocaleDateString(lang==='en'?'en-US':'it-IT',{month:'2-digit',year:'numeric'}); }
export function formatDateRange(start,end,lang='it'){ const s=formatMonthYear(start,lang); const e=end?formatMonthYear(end,lang):(s?(lang==='en'?'Present':'Presente'):''); if(s&&e) return `${s} → ${e}`; return s||e||''; }
export function cleanDateFields(payload, fields){ const next={...payload}; fields.forEach(f=>{ if(next[f]==='') next[f]=null; }); return next; }
export function restoreScrollAfter(fn){ const y=typeof window!=='undefined'?window.scrollY:0; return Promise.resolve(fn()).finally(()=>{ if(typeof window!=='undefined') requestAnimationFrame(()=>window.scrollTo({top:y,behavior:'instant'})); }); }
export function normalizeCategory(cat){ const map={ 'Digital & Data':'Digital','Digital, AI & Automazione':'Digital','Data Analysis & Reporting':'Digital','Project & Process Management':'Gestione Progetti','Comunicazione & Public Speaking':'Comunicazione','Leadership & People Management':'Leadership','Fashion, Product & Manufacturing':'Tecniche di Settore','Finance, Legal & Business':'Tecniche di Settore','Problem Solving & Continuous Improvement':'Analisi & Problem Solving','Creatività, Design & UX':'Creatività & Design','Altro / Settoriale':'Altro' }; return SKILL_CATEGORIES.includes(cat)?cat:(map[cat]||'Altro'); }
export function isVisibleInLang(row, lang){ return !row?.content_lang || row.content_lang==='all' || row.content_lang===lang; }
export function fieldVisible(row, field){ if(row?.is_hidden) return false; const v=row?.cv_visibility || {}; if(Object.prototype.hasOwnProperty.call(v, field)) return Boolean(v[field]); return true; }
export function computeSkillInsights(skills){ const visible=(skills||[]).filter(s=>!s.is_hidden); const byCat=new Map(SKILL_CATEGORIES.map(c=>[c,[]])); visible.forEach(s=>{ const cat=normalizeCategory(s.category); byCat.get(cat).push(Number(s.rating||0)); }); const radar=SKILL_CATEGORIES.map(category=>{ const values=byCat.get(category)||[]; const avg=values.length?values.reduce((a,b)=>a+b,0)/values.length:0; return {category,count:values.length,avg:Number(avg.toFixed(2))}; }); const coverage=radar.filter(r=>r.count>0).length/SKILL_CATEGORIES.length; const avg=visible.length?visible.reduce((a,s)=>a+Number(s.rating||0),0)/visible.length:0; const score=Math.max(0,Math.min(100,Math.round((avg/5)*82+coverage*18))); const weak=radar.filter(r=>r.avg>0&&r.avg<3.5).sort((a,b)=>a.avg-b.avg).slice(0,3); const empty=radar.filter(r=>r.count===0&&r.category!=='Altro').slice(0,3); const suggestions=[...weak,...empty].slice(0,5).map(r=>({category:r.category,reason:r.count?`Media ${r.avg}/5: area da rafforzare.`:'Categoria non ancora coperta nel profilo.',skills:suggestSkillsForCategory(r.category),courses:COURSE_LIBRARY[r.category]||COURSE_LIBRARY.Altro})); return {radar,score,suggestions}; }
function suggestSkillsForCategory(category){ const map={ Digital:['Excel avanzato','Power BI','AI tools'], 'Gestione Progetti':['Agile planning','Roadmap management','Project management'], Comunicazione:['Public speaking','Copywriting','Presentazioni efficaci'], Leadership:['Feedback','Coaching','Team management'], 'Tecniche di Settore':['Industrializzazione','Qualità prodotto','Supply chain'], 'Analisi & Problem Solving':['Root cause analysis','Kaizen','Problem solving A3'], 'Creatività & Design':['Design thinking','Figma','UX research'], Altro:['Certificazione specialistica','Portfolio project','Tool verticale'] }; return map[category]||map.Altro; }
