export const DICT = {
  it: {
    appName:'QR Curriculum', dashboard:'Dashboard', analytics:'Analytics', radarSkill:'Radar Skill', publicProfile:'Profilo pubblico', logout:'Logout', downloadPdf:'Scarica PDF',
    homeBadge:'CV digitale + QR + Analytics', homeTitle:'Il tuo profilo professionale sempre aggiornato, misurabile e condivisibile.', homeSubtitle:'Crea un CV online con URL professionale, QR code tracciato, analytics visite e radar delle competenze.',
    homeCta:'Crea il tuo QR Curriculum', homeSecondary:'Vedi Radar Skill', homeFeature1:'CV pubblico', homeFeature2:'QR tracking', homeFeature3:'Analytics', homeFeature4:'Radar skill', homeDesc1:'URL semplice e professionale nel formato /qrcv/nomeutente.', homeDesc2:'Il QR contiene il parametro di tracking e registra le scansioni.', homeDesc3:'Visualizzazioni, scansioni e andamento degli ultimi 30 giorni.', homeDesc4:'Valuta le skill e ricevi suggerimenti su competenze e corsi.', sectionWorkDesc:'Ruoli, aziende e periodi lavorativi.', sectionEduDesc:'Scuole, università, corsi e certificazioni.', sectionLangDesc:'Lingue conosciute e livello.', sectionSkillsDesc:'Skill con categoria e valutazione da 1 a 5.', sectionAwardsDesc:'Premi, riconoscimenti e risultati rilevanti.', sectionProjectsDesc:'Progetti personali, aziendali o professionali.', sectionCasesDesc:'Problema, soluzione e impatto ottenuto.', howTitle:'Come funziona', howSubtitle:'Un flusso semplice: compili, condividi, misuri.', step1:'Inserisci dati, esperienze, progetti e skill.', step2:'Ottieni link pubblico e QR code tracciato.', step3:'Controlli analytics e radar competenze.', privacy:'Privacy', cookie:'Cookie',
    login:'Accedi', signup:'Registrati', email:'Email', password:'Password', save:'Salva dati', saving:'Salvataggio...', personalInfo:'Informazioni personali', personalInfoDesc:'Questi dati compongono intestazione, link e profilo pubblico.', profileImageUrl:'URL foto profilo', about:'Chi sono', publicCv:'CV pubblico',
    add:'Aggiungi', edit:'Modifica', delete:'Elimina', cancel:'Annulla', close:'Chiudi modulo', saveClose:'Salva e chiudi', saveAddAnother:'Salva e aggiungi un altro', update:'Aggiorna elemento', hidden:'Nascosto', hideFromCv:'Nascondi dal CV', hideDescription:'Nascondi solo descrizione nel CV', hideScore:'Nascondi punteggio sul CV', noItems:'Nessun elemento inserito. Clicca su “Aggiungi” per iniziare.', confirmDelete:'Vuoi eliminare questo elemento?',
    showField:'Mostra nel CV', contentLang:'Lingua contenuto', both:'Tutte', italian:'Italiano', english:'Inglese', work:'Esperienze', education:'Formazione', languages:'Lingue', skills:'Competenze', awards:'Premi', projects:'Progetti', caseStudies:'Case Study',
    skillName:'Competenza', skillCategory:'Categoria', rating:'Valutazione 1-5', newSkillNotice:'Non presente nel catalogo: puoi aggiungerla come nuova competenza.', catalogHint:'Cerca prima nel catalogo globale. Se non trovi la skill, puoi inserirla come nuova.',
    views:'Visualizzazioni profilo', scans:'Scansioni QR', totalEvents:'Eventi totali', last30:'Ultimi 30 giorni', dailyTrend:'Andamento giornaliero', lastEvents:'Ultimi eventi', noEvents:'Nessun evento registrato.',
    radarTitle:'Radar delle tue competenze', radarDesc:'Il radar mostra la media per categoria. Sotto trovi le competenze ordinate alfabeticamente, il punteggio utente e i videocorsi consigliati.', userScore:'Punteggio utente', suggestedSkills:'Skill suggerite', suggestedCourses:'Videocorsi consigliati', suggestedCoursesHelp:'I videocorsi sono suggerimenti automatici: il sistema guarda le categorie scoperte o con media più bassa e propone possibili percorsi di crescita.', skillList:'Elenco competenze',
    present:'Presente', from:'Da', to:'a', profileNotFound:'Profilo non trovato o non pubblico.', loading:'Caricamento...', saved:'Dati salvati correttamente.', role:'Ruolo', company:'Azienda', title:'Titolo', description:'Descrizione', start:'Inizio', end:'Fine', date:'Data', issuer:'Ente', institution:'Istituto', level:'Livello', portfolioPhrase1:'Ho reso il mio CV interattivo.', portfolioPhrase2:'Scansiona per vedere il mio portfolio completo.'
  },
  en: {
    appName:'QR Curriculum', dashboard:'Dashboard', analytics:'Analytics', radarSkill:'Skill Radar', publicProfile:'Public profile', logout:'Logout', downloadPdf:'Download PDF',
    homeBadge:'Digital CV + QR + Analytics', homeTitle:'Your professional profile, always updated, measurable and easy to share.', homeSubtitle:'Create an online CV with a professional URL, tracked QR code, profile analytics and a skill radar.',
    homeCta:'Create your QR Curriculum', homeSecondary:'View Skill Radar', homeFeature1:'Public CV', homeFeature2:'QR tracking', homeFeature3:'Analytics', homeFeature4:'Skill radar', homeDesc1:'Simple professional URL in /qrcv/username format.', homeDesc2:'The QR includes a tracking parameter and records scans.', homeDesc3:'Profile views, scans and last-30-days trend.', homeDesc4:'Rate skills and get suggestions on competencies and courses.', sectionWorkDesc:'Roles, companies and work periods.', sectionEduDesc:'Schools, universities, courses and certifications.', sectionLangDesc:'Known languages and level.', sectionSkillsDesc:'Skills with category and rating from 1 to 5.', sectionAwardsDesc:'Awards, recognitions and relevant achievements.', sectionProjectsDesc:'Personal, company or professional projects.', sectionCasesDesc:'Problem, solution and achieved impact.', howTitle:'How it works', howSubtitle:'A simple flow: fill in, share, measure.', step1:'Add your details, experience, projects and skills.', step2:'Get a public link and a tracked QR code.', step3:'Monitor profile analytics and your skill radar.', privacy:'Privacy', cookie:'Cookie',
    login:'Login', signup:'Sign up', email:'Email', password:'Password', save:'Save data', saving:'Saving...', personalInfo:'Personal information', personalInfoDesc:'These details build your header, public link and public profile.', profileImageUrl:'Profile photo URL', about:'About me', publicCv:'Public CV',
    add:'Add', edit:'Edit', delete:'Delete', cancel:'Cancel', close:'Close form', saveClose:'Save and close', saveAddAnother:'Save and add another', update:'Update item', hidden:'Hidden', hideFromCv:'Hide from CV', hideDescription:'Hide only description in CV', hideScore:'Hide score on CV', noItems:'No items yet. Click “Add” to start.', confirmDelete:'Do you want to delete this item?',
    showField:'Show on CV', contentLang:'Content language', both:'All', italian:'Italian', english:'English', work:'Experience', education:'Education', languages:'Languages', skills:'Skills', awards:'Awards', projects:'Projects', caseStudies:'Case Studies',
    skillName:'Skill', skillCategory:'Category', rating:'Rating 1-5', newSkillNotice:'Not in the catalog: you can add it as a new skill.', catalogHint:'Search the global catalog first. If you cannot find the skill, add it as new.',
    views:'Profile views', scans:'QR scans', totalEvents:'Total events', last30:'Last 30 days', dailyTrend:'Daily trend', lastEvents:'Latest events', noEvents:'No events recorded.',
    radarTitle:'Your skill radar', radarDesc:'The radar shows the category average. Below you get alphabetically sorted skills, your user score and recommended video courses.', userScore:'User score', suggestedSkills:'Suggested skills', suggestedCourses:'Recommended video courses', suggestedCoursesHelp:'Video courses are automatic suggestions: the system checks uncovered or weaker categories and proposes possible growth paths.', skillList:'Skill list',
    present:'Present', from:'From', to:'to', profileNotFound:'Profile not found or not public.', loading:'Loading...', saved:'Data saved successfully.', role:'Role', company:'Company', title:'Title', description:'Description', start:'Start', end:'End', date:'Date', issuer:'Issuer', institution:'Institution', level:'Level', portfolioPhrase1:'I made my CV interactive.', portfolioPhrase2:'Scan to view my full portfolio.'
  }
};
export function getInitialLang(){ if(typeof window==='undefined') return 'it'; return localStorage.getItem('qrcv-lang') || 'it'; }
