'use client';
import { useEffect, useRef, useState } from 'react';
import { useParams, useSearchParams } from 'next/navigation';
import QRCode from 'qrcode';
import { supabase } from '@/lib/supabaseClient';
import { makeQrUrl } from '@/lib/helpers';
import CvTemplate from '@/components/CvTemplate';
import { LanguageToggle, useLang } from '@/components/LanguageProvider';
export default function PublicQrCvPage(){const{slug}=useParams();const params=useSearchParams();const{t}=useLang();const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[data,setData]=useState(null);const[qrCode,setQrCode]=useState('');const tracked=useRef(false);useEffect(()=>{async function load(){const{data:p,error:e}=await supabase.from('personal_info').select('*').eq('public_slug',slug).eq('is_public',true).maybeSingle();if(e||!p){setError(t.profileNotFound);setLoading(false);return}const next={personal_info:p};for(const table of ['work_experiences','educations','languages','skills','awards','projects','case_studies']){const{data:rows}=await supabase.from(table).select('*').eq('user_id',p.user_id).eq('is_hidden',false).order('created_at',{ascending:false});next[table]=rows||[]}setData(next);QRCode.toDataURL(makeQrUrl(slug),{width:180,margin:1}).then(setQrCode);setLoading(false);if(!tracked.current){tracked.current=true;const base={profile_user_id:p.user_id,public_slug:slug,path:typeof window!=='undefined'?window.location.pathname:'',referrer:typeof document!=='undefined'?document.referrer:'',user_agent:typeof navigator!=='undefined'?navigator.userAgent:''};await supabase.from('analytics_events').insert({...base,event_type:'profile_view'});if(params.get('qr')==='1')await supabase.from('analytics_events').insert({...base,event_type:'qr_scan'});}}if(slug)load()},[slug,params,t.profileNotFound]);async function downloadPdf(){const html2pdf=(await import('html2pdf.js')).default;html2pdf().set({margin:6,filename:'CV.pdf',image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'}}).from(document.getElementById('cv-document')).save()}if(loading)return <p style={{padding:24}}>{t.loading}</p>;if(error)return <p className="error" style={{padding:24}}>{error}</p>;return <main className="publicPage"><div className="publicActions"><button className="btn primary" onClick={downloadPdf}>{t.downloadPdf}</button> <LanguageToggle/></div><CvTemplate data={data} qrCode={qrCode}/></main>}
